# ChatClient 配置示例
yxboot:
  llm:
    client:
      # 缓存配置
      cache-enabled: true
      max-cache-size: 100
      cache-expire-minutes: 30
      
      # 超时配置
      default-timeout-seconds: 60
      
      # 健康检查配置
      health-check-enabled: true
      health-check-interval-minutes: 5
      
      # 重试配置
      retry:
        enabled: true
        max-attempts: 3
        delay-millis: 1000
        multiplier: 2.0

# 日志配置
logging:
  level:
    com.yxboot.llm.client: DEBUG
    com.yxboot.llm.chat: INFO
    com.yxboot.llm.provider: INFO 