spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/yxboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  # Redis 若设有密码自行添加配置password
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

  # 邮件配置
  mail:
    host: smtp.example.com # 邮箱服务器地址
    port: 587 #  邮箱服务器端口
    username: your-email@example.com #  邮箱账号
    password: your-password #  邮箱密码
    properties:
      mail:
        smtp:
          auth: true # 开启认证
          starttls: # 开启TLS
            enable: true #  开启
            required: true #  必须


yxboot:
  # llm 客户端配置
  llm:
    client:
      # 缓存配置
      cache-enabled: true
      max-cache-size: 100
      cache-expire-minutes: 30
      
      # 超时配置
      default-timeout-seconds: 60
      
      # 健康检查配置
      health-check-enabled: true
      health-check-interval-minutes: 5
      
      # 重试配置
      retry:
        enabled: true
        max-attempts: 3
        delay-millis: 1000
        multiplier: 2.0

    embedding:
      client:
        # 缓存配置
        cache-enabled: true
        max-cache-size: 100
        cache-expire-minutes: 30
        
        # 超时配置
        default-timeout-seconds: 60
        
        # 健康检查配置
        health-check-enabled: true
        health-check-interval-minutes: 5
        
        # 重试配置
        retry:
          enabled: true
          max-attempts: 3
          delay-millis: 1000
          multiplier: 2.0

      qdrant:
        host: localhost
        port: 6333
        grpc-port: 6334
        https: false
        api-key: 
        default-collection-name: documents

  upload:
    model: local
    local:
      enable: true
      path-prefix: /xxx/xxx/xxx/xxx/
      url-prefix: http://ip:port/
      rewrite-file-name: true
    oss:
      enable: true
      endpoint: xxx
      accessKey: xxx
      secretKey: xxx
      bucketName: xxx
      rewrite-file-name: true
