spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/yxboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  # Redis 若设有密码自行添加配置password
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

yxboot:
  upload:
    model: local
    local:
      enable: true
      path-prefix: /Users/liangliang/IdeaProjects/zuolaoshi/yunxing-api/attrs/
      url-prefix: http://192.168.0.72:9898/
      rewrite-file-name: true
    oss:
      enable: true
      endpoint: xxx
      accessKey: xxx
      secretKey: xxx
      bucketName: xxx
      rewrite-file-name: true